$ANSIBLE_VAULT;1.1;AES256
31633433323466613232636230363166323230653465643761323564383431333961636161653830
6166353665393330626533623135633931626532316262360a653861643831373237643431366166
33343862663266333634306663313935383033393565306261613634336432343230663164323263
6632323161383433640a333135646439373035626238393166383162396336643230393838626433
61613565623966666233313364326330383861656562653531326562666231663439316432373963
30373033366638373961343163613366353431336566616465326166616532353930336161383739
33366166303730663333623432373135663961636136646361666330316566386538396432313433
38383333623464636661663963353564663034626339303035383536333533656364643533303862
66636238396435376639353831396431646266373433336539356633386637333333393463376262
38373761313164386263323433306236616430663461393838333031326433626661636466633030
30363262366530333335313834636233303033626434633936653837366333373730613066613630
33666466373638653735623461303132383561363531646161663965653932643336363462383130
63383661663539613566666335346632616635653939336533376465623966646531353737383331
37663837363538363032383039363938333533373762353865633937613230326161346333643330
37646634393861363263383163663733613931393931366364373834653933353165333833656632
34303063613266353039
