[tool.basedpyright]
reportUnknownVariableType = "none"
reportUnknownParameterType = "none"
reportUnknownMemberType = "none"
reportMissingTypeStubs = "none"

[tool.pytest.ini_options]
addopts = "--cov=. --cov-fail-under=70"

[tool.coverage.run]
omit = [ "tests/*", "*/__init__.py" ]
