$ANSIBLE_VAULT;1.1;AES256
38653463613966636538626531663233343162373131343438626466303734613232633433613834
3065393162643062613132306634363562343064316665380a343934316463393339336635376436
63636233373536616335653239363338353137333831623562633532383635353764653932663035
3461666635366437660a373639353932323465306338633630336130393838343265393262633035
35343532396336633037313330666166313465613466646531333633356637373138646461336462
39323864313964313166306635613936313463626264623762343961366537323639363435353632
30316234633431393639316531633132653364626536666239626135376164373831613338643463
66396231323233613436323361303534376264613535386265396266643835323961626539613039
35666634363034643362613230353735313761376537393034333164323435316430663065396534
36623362346664303434326330316562653439366334626139643361616637373637353432646437
63316132656330376636383539376164353333663837373631663137363737373033623733386335
37336630346532356433353861316238393464373336666230313537636635633832383365316661
30376130393139353737356231393638303535373865386664343363313863613762343932373331
32396661373033313265313236363930343333643934353263333233643533323961666365306432
61653037306537366334343033313337306338613238613264396464386139366137386135373831
39656162616139643139
